<a href="https://colab.research.google.com/github/pranavrao87/Machine-Learning/blob/Tensors/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook is some fundamental concepts of tensors using tensorflow

Covers:
- Intro to tensors
- get info from tensors
- manipulating tensors
- tensors and NumPy
- using @tf.function (a way to speed up regular python functions)
- Using GPUs w/ TensorFlow or (TPUs)
- examples/exercises

## Intro to tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
# Create tensors w/ tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check num of dimensions of a tensor (ndim stans for # of dimensions)
scalar.ndim

0

In [7]:
# Create a vector --> (direction and magnitude)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check dimensions of vector (1 dimensional)
vector.ndim

1

In [10]:
# Create a matrix (2 dimensional)
matrix = tf.constant([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
#Should return 2
matrix.ndim

2

In [13]:
# Create matrix w/ specified datatype
# specify data type w/ dtype parameter, integer w/ "." = floats
another_matrix = tf.constant([[6., 9.],
                             [4., 2.],
                             [0., 1.]], dtype = tf.float16)
another_matrix  

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[6., 9.],
       [4., 2.],
       [0., 1.]], dtype=float16)>

In [15]:
# Dimensions of another_matrix should be 2
# num of dimensions is = to items in "shape()" and bc matrices are 2d
another_matrix.ndim

2

In [16]:
# Creating a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
# Should be 3 dimensional
tensor.ndim

3

#Key Ideas:

- Scalar: single number (only magnitude)
- Vector: a number w/ direction (direction AND magnitude)
  - ex. velocity
- Matrix: a 2 dimensional array of numbers
- Tensor: an n-dimensional array of numbers (where n can be any number)
  - a 0 dimensional tensor is a scalar
  - a 1 dimensional tensor is a vector

### Creating tensors w/ tf.Variable

In [18]:
# Create the same tensor(s) w/ tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [20]:
# Change elements in changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [21]:
# Use .assign() function
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [26]:
# Try to change the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [27]:
# You CANNOT modify the values of an unchangeable tensor created through tf.constant function

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [28]:
# Create two random, but same, tensors

In [31]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [32]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [35]:
# Should be equal b/c generate from same seed therefore random numbers from seed are partially generated
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [42]:
# Should be different b/c seeds are diff value
random_3 = tf.random.Generator.from_seed(7)
random_3 = random_3.normal(shape =(3,2))
random_1 == random_3


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### Shuffle the order of elements in a tensor

In [47]:
# Shuffle a tensor, valuable for when you want to shuffle data so the inherent order doesn't effect learning
not_shuffled = tf.constant([[10, 7],
                              [3,4],
                              [2, 5]])
not_shuffled.ndim

2

In [48]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [50]:
# Shuffle
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [61]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#### Random and .set_seed() *exploration*

In [77]:
#Scenario 1 no global or operational seed set:
# Remember .uniform outputs values from a uniform bell distribution curve in 
#this case the maxVal value = 1
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
# results in different values every time for each tensor

tf.Tensor([0.59750986], shape=(1,), dtype=float32)
tf.Tensor([0.9099175], shape=(1,), dtype=float32)


In [79]:
#Scenario 2 only global seed set:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  
print(tf.random.uniform([1]))  
# results will be a randomly generated set of values, but will stay constant
# such that 1st tensor always holds randomly generated value X1 and 2nd tensor
# always holds randomly generated value X2 b/c second call uses different
# OPERATIONAL seed

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [85]:
#Scenario 3 only local operational seed set:
print(tf.random.uniform([1], seed=1)) 
print(tf.random.uniform([1], seed=1))


tf.Tensor([0.35958135], shape=(1,), dtype=float32)
tf.Tensor([0.8072809], shape=(1,), dtype=float32)
