<a href="https://colab.research.google.com/github/pranavrao87/Machine-Learning/blob/main/Tensors/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook is some fundamental concepts of tensors using tensorflow

Covers:
- Intro to tensors
- get info from tensors
- manipulating tensors
- tensors and NumPy
- using @tf.function (a way to speed up regular python functions)
- Using GPUs w/ TensorFlow or (TPUs)
- examples/exercises

## Intro to tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [4]:
# Create tensors w/ tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check num of dimensions of a tensor (ndim stans for # of dimensions)
scalar.ndim

0

In [6]:
# Create a vector --> (direction and magnitude)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check dimensions of vector (1 dimensional)
vector.ndim

1

In [8]:
# Create a matrix (2 dimensional)
matrix = tf.constant([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
#Should return 2
matrix.ndim

2

In [10]:
# Create matrix w/ specified datatype
# specify data type w/ dtype parameter, integer w/ "." = floats
another_matrix = tf.constant([[6., 9.],
                             [4., 2.],
                             [0., 1.]], dtype = tf.float16)
another_matrix  

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[6., 9.],
       [4., 2.],
       [0., 1.]], dtype=float16)>

In [11]:
# Dimensions of another_matrix should be 2
# num of dimensions is = to items in "shape()" and bc matrices are 2d
another_matrix.ndim

2

In [12]:
# Creating a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# Should be 3 dimensional
tensor.ndim

3

#Key Ideas:

- Scalar: single number (only magnitude)
- Vector: a number w/ direction (direction AND magnitude)
  - ex. velocity
- Matrix: a 2 dimensional array of numbers
- Tensor: an n-dimensional array of numbers (where n can be any number)
  - a 0 dimensional tensor is a scalar
  - a 1 dimensional tensor is a vector

### Creating tensors w/ tf.Variable

In [14]:
# Create the same tensor(s) w/ tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
# Change elements in changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [17]:
# Use .assign() function
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# Try to change the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [20]:
# You CANNOT modify the values of an unchangeable tensor created through tf.constant function

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [21]:
# Create two random, but same, tensors

In [22]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [23]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [24]:
# Should be equal b/c generate from same seed therefore random numbers from seed are partially generated
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [25]:
# Should be different b/c seeds are diff value
random_3 = tf.random.Generator.from_seed(7)
random_3 = random_3.normal(shape =(3,2))
random_1 == random_3


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

### Shuffle the order of elements in a tensor

In [26]:
# Shuffle a tensor, valuable for when you want to shuffle data so the inherent order doesn't effect learning
not_shuffled = tf.constant([[10, 7],
                              [3,4],
                              [2, 5]])
not_shuffled.ndim

2

In [27]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [28]:
# Shuffle
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [29]:
# Create a tensor of all ones in this case a 10x7 array
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
# Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

main diff b/w NumPy and TensorFlow is that tensors can be run on a GPU (much faster for computing)

In [31]:
# Can also turn NumPy arrays into tensorFlow tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create NumPy array b/w 1 and 25
numpy_A

# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [32]:
A = tf.constant(numpy_A, shape=(2, 2, 2, 3)) #tensor
B = tf.constant(numpy_A) # vector
A, B

(<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
 array([[[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]],
 
 
        [[[13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [33]:
A.ndim

4

### Getting information from tensors

Some important attributes:
- Shape: num of elements in each dimension of tensor
- Rank: number of tensor dimensions (a scalar has rank 0, vector has rank 1, etc)
- Axis or dimension: particular dimension of a tensor
- Size: total num of items in tensor

In [34]:
# Creating a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor[0]
#returns the first set of "3 tensors" b/c the original tensor contains 2 3*4*5 tensor units

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [36]:
print(rank_4_tensor.shape) # should be [2, 3, 4, 5]
print(rank_4_tensor.ndim) # should be 4
print(tf.size(rank_4_tensor)) # should be 2*3*4*5 = 120

(2, 3, 4, 5)
4
tf.Tensor(120, shape=(), dtype=int32)


In [37]:
# Get various attribtues of tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elemebts along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total num of elements in tensor as tf tensor: ", tf.size(rank_4_tensor))
print("Total num of elements in tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elemebts along the 0 axis:  2
Elements along the last axis:  5
Total num of elements in tensor as tf tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total num of elements in tensor:  120


### Indexing tensors

Tensors can be indexed similar to Python lists

In [38]:
rand_list = [1, 2, 3, 4]
rand_list[:2]

[1, 2]

In [39]:
# Get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [40]:
# Get first element from each dimension from each index except for final dimension
rank_4_tensor[:1, :1, :1, :]
# can either leave blank or put empty colon

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [41]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [42]:
# More examples
rank_4_tensor[:1, :, :, :1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [43]:
rank_4_tensor[:, :1, :2, :]

<tf.Tensor: shape=(2, 1, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([1, 2, 3, 4], shape = (2, 2))
# or rank_2_tensor = tf.constant([[1, 2],
#                                 [3, 4]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 TensorShape([2, 2]),
 2)

In [45]:
#last item of each our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [46]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # 3 dots indicate every axis before
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [47]:
# Another method alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 refers to final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [48]:
tf.expand_dims(rank_2_tensor, axis=0) # expands 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [49]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**

" +, -, *, /"

In [50]:
tensor = tf.constant([[10, 7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [51]:
# Original tensor is unchanged
tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [52]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [53]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [54]:
# Division
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [55]:
# Tensorflow built in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

In ML, matrix multiplicatoin is a very common tensor operation

Two rules for tensors (matrices) need to fulfil if multiplication is going to be done

1. inner dimensions must match
2. resulting matrix has shape of outter dimensions



In [56]:
# Matric multiplication in tf
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [57]:
ltensor = tf.constant([[1, 2, 5],
                       [7, 2, 1],
                       [3, 3, 3]])
rtensor = tf.constant([[3, 5],
                       [6,7],
                       [1, 8]])
tf.matmul(ltensor, rtensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [58]:
# NOT THE SAME as tensor * tensor b/c that is only by index
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [59]:
# Matrix multiplication w/ Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
# Create tensor (3, 2) tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# Create another (3, 2) tensor
Y = tf.constant([[7,8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [61]:
# Matmul of same shape
tf.reshape(Y, shape=(2,3))
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [62]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
#Alternate way
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [64]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [65]:
# Changing the shape of X instead of Y
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [66]:
# Can do same w/ transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [67]:
# Try matrix multiplication w/ transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as dot product.

2 diff ways:
1. tf.matmul()
2. tf.tensordot()

In [68]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [69]:
# Perform dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [70]:
# Perform matrix multiplication b/w X and Y (transpose)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [71]:
#Perform matrix multiplication b/w X and Y (reshape)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [72]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y: ")
print(Y, "\n")
print("Y reshaped to (2,3): ")
print(tf.reshape(Y, (2,3)), "\n")
print("Y transposed: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [73]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

*When performing matrix multiplication on two tensors and one of the axes doesn't line up, transposition is more common than reshaping the matrix to perform operation. *

### Changing the datatype of a tensor

In [74]:
# Create a new tensor w/ default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [75]:
C = tf.constant([7 , 10])
C.dtype

tf.int32

In [76]:
# Change from float32 --> float 16 (reduced precision for faster processing)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [77]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [78]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16, E_float16.dtype 

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

### Aggregting tensors

Aggregating tensors = condensing tensors from multiple values down to smaller amount of values

In [79]:
# Get absolute values
D = tf.constant([-7, -10])
D 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [80]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Different forms of aggregation:
- Get min of tensor
- Get max of tensor
- Get mean of tensor
- Get sum of tensor

In [81]:
# Create a random tensor w/ values b/w 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([91,  5,  4, 72, 17, 57, 68, 74, 97, 74, 48, 63, 95,  6, 10, 11,  2,
       91, 18, 24, 62, 90, 62, 26, 29, 87, 76, 32, 26, 95, 62, 52, 43, 96,
       77, 86, 53, 19, 84, 36, 59, 10, 66, 13, 14, 85, 32, 75, 65, 91])>

In [82]:
tf.size(E), E.shape, E.ndim


(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [83]:
# Find min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [84]:
# Find max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [85]:
# Find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [86]:
# Find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2630>

In [87]:
# Find variance - squared of standard deviation
print(tf.math.reduce_variance(tf.cast(E, dtype=tf.float64)))
# int won't work, but float will work
# Alternatively
import tensorflow_probability as tfp
tfp.stats.variance(E)

tf.Tensor(938.96, shape=(), dtype=float64)


<tf.Tensor: shape=(), dtype=int64, numpy=939>

In [88]:
# Find Standard Deviation - amount of dispersion of data or spread from the mean
tf.math.reduce_std(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=30.642454209805063>

### Find positional max and minimum



In [89]:
# Create a new tensor for finding positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [90]:
# Find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [91]:
# Index on largest val in position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [92]:
# Find max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [93]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [94]:
# Find positinal min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [95]:
# Find min using positional min index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [96]:
Z = tf.random.uniform(shape=([2,10]))
Z

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256],
       [0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ]],
      dtype=float32)>

In [97]:
tf.argmax(Z)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1])>

In [98]:
tf.argmax(Z, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([6, 9])>

### Squeezing tensors (removing all single dimensions)

In [99]:
# Create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [100]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [101]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hote encoding tensors

In [102]:
# Create a list of indices
some_list = [0, 1, 2, 3] # Could represent red, green, blue, purple

# One-hot encode list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [103]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

In [104]:
tf.one_hot(some_list, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

### More math operations

- Squaring
- log
- root
- and more

In [105]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [106]:
# Squaring tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [107]:
# Square root tensor, method requires non-int type
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [108]:
# Logarithm
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [109]:
# Cosine
Y = tf.random.uniform(shape=[10])
tf.cos(tf.cast(Y, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.77258664, 0.8849178 , 0.59703654, 0.968369  , 0.7444044 ,
       0.6274142 , 0.584325  , 0.7321426 , 0.93962747, 0.8539938 ],
      dtype=float32)>

In [110]:
# Cumulative sum along certain axis ---> tf.cumsum([a, b, c]) = [a, a + b, a + b + c]
X = tf.range(1, 20)
tf.cumsum(X)

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)>

In [111]:
# Floor division (integer division essentially cuts of decimal places)
W = tf.random.uniform(shape=[10], dtype=tf.float16)
tf.math.floordiv(W[tf.argmax(W)], W[tf.argmin(W)])

<tf.Tensor: shape=(), dtype=float16, numpy=21.0>

### Tensors and NumPy

Tensorflow interacts w/ NumPy arrays

Tensors run faster on GPU and TPUs than typical arrays

In [112]:
# Create a tensor directly from NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [113]:
# Method 1: Convert tensor back to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [114]:
# Method 2: Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [115]:
# Default types of each are slightly diff
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check dtypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [116]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [117]:
!nvidia-smi

Tue May 16 01:50:43 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    27W /  70W |    375MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Note - If you have access to a CUDA-enabled GPU TensorFLow will automatically use it whenever possible