<a href="https://colab.research.google.com/github/pranavrao87/Machine-Learning/blob/Tensors/extra_randomTensor_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Some extra practice based on the random generation of tensors and seeds

##### All practice was based on officaial tensor flow documentation found here: https://www.tensorflow.org/api_docs/python/tf/random/set_seed 



#### Random and .set_seed() *exploration*

In [ ]:
#Scenario 1 no global or operational seed set:
# Remember .uniform outputs values from a uniform bell distribution curve in 
#this case the maxVal value = 1
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
# results in different values every time for each tensor

tf.Tensor([0.53272355], shape=(1,), dtype=float32)
tf.Tensor([0.01041746], shape=(1,), dtype=float32)


In [ ]:
#Scenario 2 only global seed set:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  
print(tf.random.uniform([1]))  
# results will be a randomly generated set of values, but will stay constant
# such that 1st tensor always holds randomly generated value X1 and 2nd tensor
# always holds randomly generated value X2 b/c second call uses different
# OPERATIONAL seed

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
#Scenario 3 only local operational seed set:
print(tf.random.uniform([1], seed=1)) 
print(tf.random.uniform([1], seed=1))

def f():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b

@tf.function    #@tf.function acts as rerun of program
def g():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b

print(f())
print(g())

#results in diff values for every call to program, but same values for reruns

tf.Tensor([0.8399737], shape=(1,), dtype=float32)
tf.Tensor([0.25597703], shape=(1,), dtype=float32)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8998898], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.576313], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [ ]:
#Scenario 4 when both global and operational seed set to sam value
# both seeds are used to determine random val

tf.random.set_seed(69)
print(tf.random.uniform([1], seed=69))
print(tf.random.uniform([1], seed=69))
#Every rerun of program keeps values constant although each tensor has a different value

tf.Tensor([0.9949682], shape=(1,), dtype=float32)
tf.Tensor([0.95429695], shape=(1,), dtype=float32)
