<a href="https://colab.research.google.com/github/pranavrao87/Machine-Learning/blob/Tensors/extra_randomTensor_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Some extra practice based on the random generation of tensors and seeds

##### All practice was based on officaial tensor flow documentation found here: https://www.tensorflow.org/api_docs/python/tf/random/set_seed 



#### Random and .set_seed() *exploration*

In [2]:
import tensorflow as tf

In [ ]:
#Scenario 1 no global or operational seed set:
# Remember .uniform outputs values from a uniform bell distribution curve in 
#this case the maxVal value = 1
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
# results in different values every time for each tensor

tf.Tensor([0.53272355], shape=(1,), dtype=float32)
tf.Tensor([0.01041746], shape=(1,), dtype=float32)


In [ ]:
#Scenario 2 only global seed set:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  
print(tf.random.uniform([1]))  
# results will be a randomly generated set of values, but will stay constant
# such that 1st tensor always holds randomly generated value X1 and 2nd tensor
# always holds randomly generated value X2 b/c second call uses different
# OPERATIONAL seed

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
#Scenario 3 only local operational seed set:
print(tf.random.uniform([1], seed=1)) 
print(tf.random.uniform([1], seed=1))

def f():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b

@tf.function    #@tf.function acts as rerun of program
def g():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b

print(f())
print(g())

#results in diff values for every call to program, but same values for reruns

tf.Tensor([0.8399737], shape=(1,), dtype=float32)
tf.Tensor([0.25597703], shape=(1,), dtype=float32)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8998898], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.576313], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [ ]:
#Scenario 4 when both global and operational seed set to sam value
# both seeds are used to determine random val

tf.random.set_seed(69)
print(tf.random.uniform([1], seed=69))
print(tf.random.uniform([1], seed=69))
#Every rerun of program keeps values constant although each tensor has a different value

tf.Tensor([0.9949682], shape=(1,), dtype=float32)
tf.Tensor([0.95429695], shape=(1,), dtype=float32)


In [4]:
# 5 examples of Random tensors
random_1 = tf.random.Generator.from_seed(1)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(2)
random_2 = random_2.normal(shape=(3,2))
random_3 = tf.random.Generator.from_seed(30)
random_3 = random_3.normal(shape=(3,2))
random_4 = tf.random.Generator.from_seed(400)
random_4 = random_4.normal(shape=(3,2))
random_5 = tf.random.Generator.from_seed(55)
random_5 = random_5.normal(shape=(3,2))

random_1, random_2, random_3, random_4, random_5

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.43842274, -0.53439844],
        [-0.07710262,  1.5658046 ],
        [-0.1012345 , -0.2744976 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1012345 , -0.2744976 ],
        [ 1.4204658 ,  1.2609464 ],
        [-0.43640924, -1.9633987 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.8357487 ,  0.20849545],
        [ 1.4040174 , -2.735283  ],
        [ 1.2232229 , -1.8653691 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.4570636 , -0.06070056],
        [ 0.32132152, -0.8614107 ],
        [ 1.3434758 , -0.384727  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.04082382,  2.6791053 ],
        [ 1.0914806 ,  0.33149615],
        [-0.67958915,  0.44723678]], dtype=float32)>)

In [24]:
#Shuffle all 5 using different seeds and combinations of operational and global seeds
tf.random.shuffle(random_1) #returns random order of first dimension of tensor
tf.random.shuffle(random_4, seed=5) # random order stays constant
tf.random.shuffle(random_5) #only randomizes order of first dimension of tensor
random_1, random_4, random_5


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.43842274, -0.53439844],
        [-0.07710262,  1.5658046 ],
        [-0.1012345 , -0.2744976 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.4570636 , -0.06070056],
        [ 0.32132152, -0.8614107 ],
        [ 1.3434758 , -0.384727  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.04082382,  2.6791053 ],
        [ 1.0914806 ,  0.33149615],
        [-0.67958915,  0.44723678]], dtype=float32)>)

In [40]:
tf.random.set_seed(420)
tf.random.shuffle(random_2, seed=33)
random_2
#returns same order w/ both global and operational level seed present

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.1012345 , -0.2744976 ],
       [ 1.4204658 ,  1.2609464 ],
       [-0.43640924, -1.9633987 ]], dtype=float32)>

In [36]:
tf.random.shuffle(random_3, seed=38)
#returns diff order w/ operational level seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.4040174 , -2.735283  ],
       [ 0.8357487 ,  0.20849545],
       [ 1.2232229 , -1.8653691 ]], dtype=float32)>