<a href="https://colab.research.google.com/github/pranavrao87/Machine-Learning/blob/main/Tensors/tensor_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf

In [12]:
# Creating a scalar
A = tf.constant(1)
A

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
# Check properties of scalar
A.shape, tf.rank(A), tf.size(A)

(TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [10]:
# Creating a vector
B = tf.constant([1, 2, 3, 4, 5, 6, 7, 8], dtype=tf.float32)
B

<tf.Tensor: shape=(8,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)>

In [16]:
# Check properties of vector
B.shape, tf.rank(B), tf.size(B)

(TensorShape([8]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [9]:
# Creating a matrix
C = tf.constant([1, 2, 3, 4, 5, 6, 7, 8], dtype=tf.float32, shape=[2, 4])
C

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [17]:
# Check properties of matrix
C.shape, tf.rank(C), tf.size(C)

(TensorShape([2, 4]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [8]:
# Creating a tensor
D = tf.constant([1, 2, 3, 4, 5, 6, 7, 8], dtype=tf.float32, shape=[2, 2, 2])
D

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]], dtype=float32)>

In [18]:
# Check properties of tensor
D.shape, tf.rank(D), tf.size(D)

(TensorShape([2, 2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [20]:
# Create two random tensors w/ values b/w [0,1] and w/ size [5, 300]
E = tf.random.uniform(minval=0, maxval=1, dtype=tf.float32, shape=[5,300])
D = tf.random.uniform(minval=0, maxval=1, dtype=tf.float32, shape=[5,300])
E, D

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68568957, 0.2664894 , 0.51911354, ..., 0.5326425 , 0.51320124,
         0.66698444],
        [0.4041443 , 0.09420657, 0.844471  , ..., 0.63790226, 0.1628921 ,
         0.5862659 ],
        [0.91919637, 0.8834492 , 0.7939255 , ..., 0.1611917 , 0.6044657 ,
         0.6462759 ],
        [0.35312784, 0.8410202 , 0.37143242, ..., 0.01890993, 0.81857324,
         0.22181976],
        [0.0356549 , 0.68998885, 0.4289987 , ..., 0.21584237, 0.97913945,
         0.05594397]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.5772563 , 0.829689  , 0.2680533 , ..., 0.15931082, 0.6277517 ,
         0.6267731 ],
        [0.318228  , 0.92214906, 0.21026611, ..., 0.8895674 , 0.10025179,
         0.27956533],
        [0.61641896, 0.43719792, 0.03646648, ..., 0.9929749 , 0.19485533,
         0.33670962],
        [0.54557323, 0.7735615 , 0.15404654, ..., 0.6987845 , 0.14473963,
         0.8359544 ],
        [0.60699

In [24]:
# Multiply both matrices using matrix multiplication
print(tf.matmul(E, tf.transpose(D)))
# OR
print(tf.matmul(D, tf.transpose(E)))

tf.Tensor(
[[77.69507  84.19354  80.42373  77.72168  80.788376]
 [75.31914  80.45297  78.464294 77.42594  79.22336 ]
 [72.178345 75.20564  73.39848  68.342026 73.164276]
 [76.22011  79.51027  74.01793  75.13998  75.31381 ]
 [70.69284  76.02426  73.22025  71.070724 68.53309 ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[77.69507  75.31914  72.178345 76.22011  70.69284 ]
 [84.19354  80.45297  75.20564  79.51027  76.02426 ]
 [80.42373  78.464294 73.39848  74.01793  73.22025 ]
 [77.72168  77.42594  68.342026 75.13998  71.070724]
 [80.788376 79.22336  73.164276 75.31381  68.53309 ]], shape=(5, 5), dtype=float32)


In [36]:
# Multiply both matrices using dot product
print(tf.tensordot(E, tf.transpose(D), axes=1))
# OR 
print(tf.tensordot(D, tf.transpose(E), axes=1))

tf.Tensor(
[[77.69507  84.19354  80.42373  77.72168  80.788376]
 [75.31914  80.45297  78.464294 77.42594  79.22336 ]
 [72.178345 75.20564  73.39848  68.342026 73.164276]
 [76.22011  79.51027  74.01793  75.13998  75.31381 ]
 [70.69284  76.02426  73.22025  71.070724 68.53309 ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[77.69507  75.31914  72.178345 76.22011  70.69284 ]
 [84.19354  80.45297  75.20564  79.51027  76.02426 ]
 [80.42373  78.464294 73.39848  74.01793  73.22025 ]
 [77.72168  77.42594  68.342026 75.13998  71.070724]
 [80.788376 79.22336  73.164276 75.31381  68.53309 ]], shape=(5, 5), dtype=float32)


In [38]:
# Create rand tensor w/ values b/w [0, 1] and shape [224, 224, 3]
F = tf.random.uniform(minval=0, maxval=1, dtype=tf.float32, shape=[224, 224, 3])
F

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.18933702, 0.13485432, 0.29768312],
        [0.02303588, 0.2939589 , 0.7494451 ],
        [0.4949479 , 0.22881532, 0.6625569 ],
        ...,
        [0.02931845, 0.01648474, 0.3528527 ],
        [0.9627075 , 0.9681579 , 0.09593153],
        [0.34061027, 0.1288383 , 0.16795254]],

       [[0.63410974, 0.74327886, 0.45129704],
        [0.9259746 , 0.9876225 , 0.16102648],
        [0.37457883, 0.19167387, 0.6254437 ],
        ...,
        [0.8748456 , 0.41118038, 0.1943891 ],
        [0.91464496, 0.3440007 , 0.8555815 ],
        [0.00679624, 0.8484124 , 0.22003639]],

       [[0.18993413, 0.9367404 , 0.76818573],
        [0.46808815, 0.6990626 , 0.92095387],
        [0.6636269 , 0.6693964 , 0.70554507],
        ...,
        [0.32843792, 0.83746064, 0.31219232],
        [0.98219776, 0.893276  , 0.29025126],
        [0.2213124 , 0.63982415, 0.17675579]],

       ...,

       [[0.04118216, 0.6600311 , 0.06818032],
        [0.09

In [56]:
# Find min of tensor F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=6.4373016e-06>

In [57]:
# Find max of tensor F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999957>

In [62]:
# Create a tensor w/ random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
G = tf.random.uniform(minval=0, maxval=0, shape=[1, 224, 224, 3], dtype=tf.float32)
tf.squeeze(G).shape

TensorShape([224, 224, 3])

In [65]:
# Create a tensor with shape [10] using some values, then find the index which has the maximum value.
H = tf.random.uniform(shape=[10], dtype=tf.float32)
print(H)
H[tf.argmax(H)]

tf.Tensor(
[0.5886283  0.2973771  0.24681902 0.8618721  0.01993382 0.8052851
 0.00747478 0.38971877 0.9635532  0.7989701 ], shape=(10,), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=0.9635532>

In [71]:
tf.one_hot(H.numpy(), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>